version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      eleventy:
        patterns:
          - "@11ty*"
          - "eleventy*"
          - "@grimlink/eleventy*"
          - "@quasibit/eleventy*"
        update-types:
          - "minor"
          - "patch"
      postcss:
        patterns:
          - "postcss*"
        update-types:
          - "minor"
          - "patch"
      rollup:
        patterns:
          - "@rollup*"
          - "rollup*"
        update-types:
          - "minor"
          - "patch"
