export default {
  site: "https://fylgja.dev",
  name: "Fylgja CSS",
  description:
    "Fylgja is A Modular CSS Library for Modern Web Design Lean Maintainable and Scalable Empowers Developers to Effortlessly Build Exactly What They Need",
  foundingDate: "2021-06-22",
  themeColor: "#663399",
  themeColorDark: "#663399",
  socials: {
    github: "https://github.com/fylgja",
    bluesky: "https://bsky.app/profile/fylgja.dev",
    mastodon: "https://fosstodon.org/@fylgja",
    devto: "https://dev.to/fylgja",
  },
  twitterUser: "FylgjaDev",
  author: {
    name: "Sean van Zuidam",
    url: "https://grimlink.com",
    jobTitle: "CSS Wizard",
    description: "Frontend Developer, CSS maniac, Gamer and also the creator of Fylgja CSS",
    sameAs: [
      "https://github.com/GrimLink",
      "https://bsky.app/profile/grimlink.com",
      "https://mastodon.social/@GrimLink",
      "https://www.linkedin.com/in/seanvanzuidam",
    ],
    knowsAbout: [
      "CSS",
      "Web Development",
      "JavaScript",
      "HTML",
      "Web Design",
      "UX",
      "Accessibility",
      "Performance",
      "Design Systems",
      "Web Standards",
      "E-Commerce",
    ],
  },
};
