name: Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  NODE: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
      - run: npm install
      - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
      - uses: burnett01/rsync-deployments@5.2.1
        env:
          switches: -avzr --delete
          path: "_site/"
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: ${{ secrets.REMOTE_TARGET }}
